### ISSUE TITLE
Decide where to add uuid-ossp postgres extension

### ISSUE THREAD

**Issue by AdjectiveAllison** [cgsdev0/rollycubes#83]
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

Currently I have it on line 1 of v1 migration and it works for a new setup.

**Comment by cgsdev0** [comment]
I landed this, hopefully I don't blow up prod 😅 

https://github.com/cgsdev0/rollycubes/commit/c48d0831fcdf73955b95fa319900f360a5f882a3
