### ISSUE TITLE
make a logout button

### ISSUE THREAD

**Issue by brimonk** [cgsdev0/rollycubes#93]

**Comment by cgsdev0** [comment]
to do this, we need to make a POST to `/logout` on the auth server

this is the file we should add the request to:
https://github.com/cgsdev0/rollycubes/blob/main/client/src/api/auth.ts

docs for how to do a mutation:
https://redux-toolkit.js.org/rtk-query/usage/mutations

**Comment by cgsdev0** [comment]
done ez
